export interface RespuestaPosts {
    ok: boolean;
    posts: Post[];
}

export interface Post {
    imgs?: string[];
    _id?: string;
    mensaje?: string;
    coords?: string;
    usuario?: Usuario;
    created?: string;
    likes?:string[];
}

export interface Usuario {
    avatar?: string;
    _id?: string;
    nombre?: string;
    email?: string;
    password?: string;
}

export interface imagenTemporal{
    img:string,
    nombreImgServer:string
}

// Generated by https://quicktype.io

export interface RespuestaSubidaImagen {
    ok:           boolean;
    file:         File;
    nombreImagen: string;
}

export interface File {
    name:         string;
    data:         Data;
    size:         number;
    encoding:     string;
    tempFilePath: string;
    truncated:    boolean;
    mimetype:     string;
    md5:          string;
}

export interface Data {
    type: string;
    data: number[];
}


