// Generated by https://quicktype.io

// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface UsersReponse {
    ok:    boolean;
    users: Usuario[];
}

export interface Follow {
    _id: string;
}

export interface FollowResponse {
    ok:              boolean;
    usuario:         Usuario;
    usuarioToFollow: Usuario;
}

// Generated by https://quicktype.io

export interface UserResponse {
    ok:   boolean;
    user: Usuario;
}


export interface Follow {
    _id: string;
}



export interface PostsResponse {
    ok:    boolean;
    posts: Post[];
}

export interface Post {
    imgs?:     string[];
    _id?:      string;
    mensaje?: string;
    usuario?:  Usuario;
    likes?:    any[];
    comments?: any[];
    created?:  string;
    __v?:      number;
    coords?:string;
    posicion?:boolean;
}

export interface Usuario {
    avatar?:    string;
    imgsTemp?:  string[];
    admin?:     boolean;
    verified?:  boolean;
    _id?:       string;
    nombre?:    string;
    email?:     string;
    followers?: any[];
    following?: any[];
    __v?:       number;
    password?:string;
}






export interface imagenTemporal{
    img:string,
    nombreImgServer:string
}

// Generated by https://quicktype.io

export interface RespuestaSubidaImagen {
    ok:           boolean;
    file:         File;
    nombreImagen: string;
}

export interface File {
    name:         string;
    data:         Data;
    size:         number;
    encoding:     string;
    tempFilePath: string;
    truncated:    boolean;
    mimetype:     string;
    md5:          string;
}

export interface Data {
    type: string;
    data: number[];
}


